### ISSUE TITLE
Kong LB

### ISSUE THREAD

**Issue by aibangjuxin** [aibangjuxin/groovy#116]
Kong使用的负载均衡算法包括Round Robin、Least Connections、Consistent Hashing等。你可以在Kong的Upstream配置中设置这些算法。通过编辑Upstream，你可以选择适合你需求的负载均衡算法，例如：

```yaml
config:
  load_balancing:
    policy: round-robin
```

这样的配置将使用Round Robin算法进行负载均衡。记得在Kong的文档中查找详细的配置和算法说明。
