### ISSUE TITLE
MCI

### ISSUE THREAD

**Issue by aibangjuxin** [aibangjuxin/groovy#121]
参考：

https://cloud.google.com/kubernetes-engine/docs/concepts/multi-cluster-ingress

https://cloud.google.com/kubernetes-engine/docs/how-to/multi-cluster-ingress

**Comment by aibangjuxin** [comment]
**GKE ASM 与开源 Istio 的区别**

| 特征 | GKE ASM | 开源 Istio |
|---|---|---|
| 托管 | 是，由 Google 托管 | 否，需要自行安装和管理 |
| 集成 | 与 GKE 深度集成，开箱即用 | 需要与 Kubernetes 集成 |
| 功能 | 提供服务网格、流量管理、安全等功能 | 提供更全面的服务网格功能，包括路由、负载均衡、遥测等 |
| 易用性 | 易于设置和管理 | 安装和管理更复杂 |
| 成本 | 免费 | 需要许可证或自行托管 |

**GKE Cross-Cluster Ingress 与 Istio Kubectl Ingress**

GKE Cross-Cluster Ingress 和 Istio Kubectl Ingress 都是用于在 Kubernetes 集群之间配置 Ingress 的工具，但它们的工作方式不同：

* **GKE Cross-Cluster Ingress：**一种 Google Cloud 专有功能，允许您在多个 Kubernetes 集群之间创建 Ingress 对象。它使用 Google Cloud Load Balancer 来路由流量，并提供负载均衡、SSL 终止和监控等功能。
* **Istio Kubectl Ingress：**一个 Istio 插件，允许您使用 `kubectl` 命令创建 Ingress 对象。它使用 Istio 的 Ingress Gateway 来路由流量，并提供与 Istio 服务网格的其他功能的集成。

**主要区别：**

* **托管：**GKE Cross-Cluster Ingress 由 Google Cloud 托管，而 Istio Kubectl Ingress 则不是。
* **集成：**GKE Cross-Cluster Ingress 与 GKE 深度集成，而 Istio Kubectl Ingress 则与 Istio 服务网格集成。
* **功能：**GKE Cross-Cluster Ingress 提供更有限的功能集，专注于跨集群 Ingress，而 Istio Kubectl Ingress 提供更全面的功能集，包括与 Istio 服务网格的其他功能的集成。

**Comment by aibangjuxin** [comment]
**GKE Cross-Cluster Ingress**

GKE Cross-Cluster Ingress 是一种 Google Cloud 专有功能，允许您在多个 Kubernetes 集群之间创建 Ingress 对象。它使用 Google Cloud Load Balancer 来路由流量，并提供以下功能：

* **负载均衡：**将流量分布到集群中的多个 Pod。
* **SSL 终止：**在 Load Balancer 上终止 SSL 连接，简化了应用程序的 SSL 配置。
* **监控：**提供有关 Ingress 流量的指标和日志。
* **跨集群路由：**允许您将流量路由到其他 Kubernetes 集群中的服务。

**优点：**

* **易于使用：**使用 `kubectl` 命令即可轻松创建和管理 Ingress 对象。
* **托管：**由 Google Cloud 托管，无需自行安装和管理。
* **与 GKE 集成：**与 GKE 深度集成，开箱即用。

**缺点：**

* **功能有限：**仅提供跨集群 Ingress 的基本功能。
* **仅限 GKE：**只能在 GKE 集群中使用。

**Istio Kubectl Ingress**

Istio Kubectl Ingress 是一个 Istio 插件，允许您使用 `kubectl` 命令创建 Ingress 对象。它使用 Istio 的 Ingress Gateway 来路由流量，并提供以下功能：

* **高级路由：**支持基于路径、主机名、标头等条件的细粒度路由。
* **负载均衡：**将流量分布到集群中的多个 Pod。
* **SSL 终止：**在 Ingress Gateway 上终止 SSL 连接。
* **监控：**提供有关 Ingress 流量的指标和日志。
* **与 Istio 集成：**与 Istio 服务网格的其他功能集成，例如服务发现、流量管理和遥测。

**优点：**

* **功能强大：**提供全面的 Ingress 功能集，包括高级路由和与 Istio 的集成。
* **跨平台：**可以在任何 Kubernetes 集群中使用，无论是否使用 GKE。
* **开源：**免费且开源。

**缺点：**

* **安装和管理更复杂：**需要安装和管理 Istio 服务网格。
* **与 GKE 集成较少：**与 GKE 的集成不如 GKE Cross-Cluster Ingress。

**选择哪一个？**

选择 GKE Cross-Cluster Ingress 还是 Istio Kubectl Ingress 取决于您的特定需求：

* **如果您需要跨集群 Ingress 的基本功能，并且希望使用托管解决方案，那么 GKE Cross-Cluster Ingress 是一个不错的选择。**
* **如果您需要更高级的路由功能，并且希望与 Istio 服务网格集成，那么 Istio Kubectl Ingress 是一个更好的选择。**

**Comment by aibangjuxin** [comment]
**在 GKE 中使用 Cross-Cluster Ingress 部署端到端 (E2E) 部署的步骤**

**先决条件：**

* 两个 GKE 集群（集群 A 和集群 B）
* 在集群 A 中安装 GKE Cross-Cluster Ingress

**步骤：**

**1. 创建一个 Kubernetes Namespace**

在集群 A 中创建用于部署应用程序的 Kubernetes Namespace：

```
kubectl create namespace my-app
```

**2. 部署应用程序**

在集群 A 中的 `my-app` Namespace 中部署一个简单的应用程序（例如，Nginx）：

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.2.0/deploy/static/provider/cloud/deploy.yaml
```

**3. 创建一个 Ingress 对象**

在集群 A 中创建 Ingress 对象以公开应用程序：

```
kubectl apply -f - <<EOF
apiVersion: networking.gke.io/v1beta1
kind: Gateway
metadata:
  name: my-gateway
spec:
  defaultBackend:
    service:
      name: nginx
      port:
        number: 80
EOF
```

**4. 创建一个 Cross-Cluster Ingress**

在集群 A 中创建 Cross-Cluster Ingress 对象以将流量路由到集群 B：

```
kubectl apply -f - <<EOF
apiVersion: networking.gke.io/v1beta1
kind: CrossClusterIngress
metadata:
  name: my-cross-cluster-ingress
spec:
  gateway: my-gateway
  clusters:
  - cluster: cluster-b
    weight: 100
EOF
```

**5. 在集群 B 中创建服务**

在集群 B 中创建与集群 A 中的应用程序对应的服务：

```
kubectl apply -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: my-app
spec:
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 80
EOF
```

**6. 在集群 B 中部署应用程序**

在集群 B 中的 `my-app` Namespace 中部署应用程序：

```
kubectl apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nginx
        ports:
        - containerPort: 80
EOF
```

**测试部署：**

使用以下命令从集群 A 外部测试部署：

```
curl -H "Host: my-app.example.com" http://<EXTERNAL-IP>
```

如果一切正常，您应该会看到 Nginx 欢迎页面。

**注意：**

* 替换 `<EXTERNAL-IP>` 为集群 A 的外部 IP 地址。
* 替换 `my-app.example.com` 为 Ingress 对象中指定的域名。

**Comment by aibangjuxin** [comment]
**在 GKE 中使用 MultiClusterIngress 部署端到端 (E2E) 部署的步骤**

**先决条件：**

* 两个 GKE 集群（集群 A 和集群 B）
* 在集群 A 中安装 GKE MultiClusterIngress

**步骤：**

**1. 创建一个 Kubernetes Namespace**

在集群 A 中创建用于部署应用程序的 Kubernetes Namespace：

```
kubectl create namespace my-app
```

**2. 部署应用程序**

在集群 A 的 `my-app` Namespace 中部署一个简单的应用程序（例如，Nginx）：

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.2.0/deploy/static/provider/cloud/deploy.yaml
```

**3. 创建一个 Ingress 对象**

在集群 A 中创建 Ingress 对象以公开应用程序：

```
kubectl apply -f - <<EOF
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: my-static-ip
spec:
  rules:
  - host: my-app.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
EOF
```

**4. 创建一个 MultiClusterIngress**

在集群 A 中创建 MultiClusterIngress 对象以将流量路由到集群 B：

```
kubectl apply -f - <<EOF
apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: my-multi-cluster-ingress
spec:
  gateway: my-gateway
  clusters:
  - cluster: cluster-b
    weight: 100
EOF
```

**5. 在集群 B 中创建服务**

在集群 B 中创建与集群 A 中的应用程序对应的服务：

```
kubectl apply -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: my-app
spec:
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 80
EOF
```

**6. 在集群 B 中部署应用程序**

在集群 B 的 `my-app` Namespace 中部署应用程序：

```
kubectl apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nginx
        ports:
        - containerPort: 80
EOF
```

**测试部署：**

使用以下命令从集群 A 外部测试部署：

```
curl -H "Host: my-app.example.com" http://<EXTERNAL-IP>
```

如果一切正常，您应该会看到 Nginx 欢迎页面。

**注意：**

* 替换 `<EXTERNAL-IP>` 为集群 A 的外部 IP 地址。
* 替换 `my-app.example.com` 为 Ingress 对象中指定的域名。

**Comment by aibangjuxin** [comment]
**Ingress 对象和 MultiClusterIngress 对象之间的区别：**

* **Ingress 对象**用于在单个 Kubernetes 集群内公开服务。它将外部流量路由到集群中的服务。
* **MultiClusterIngress 对象**用于在多个 Kubernetes 集群之间公开服务。它将外部流量路由到目标集群中的服务。

**Ingress 对象是否必须：**

Ingress 对象对于在 Kubernetes 集群中公开服务是必需的。如果没有 Ingress 对象，外部流量将无法访问集群中的服务。

**何时使用 MultiClusterIngress 对象：**

MultiClusterIngress 对象在以下情况下很有用：

* 当您需要在多个 Kubernetes 集群之间公开服务时。
* 当您希望将流量路由到特定的集群时。
* 当您希望根据权重将流量分配到多个集群时。

**何时使用 Ingress 对象：**

Ingress 对象在以下情况下很有用：

* 当您只需要在单个 Kubernetes 集群中公开服务时。
* 当您希望将流量路由到集群中的所有服务时。

**总结：**

Ingress 对象对于在 Kubernetes 集群中公开服务是必需的。MultiClusterIngress 对象对于在多个 Kubernetes 集群之间公开服务很有用。

**Comment by aibangjuxin** [comment]
apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: example-mci
spec:
  clusters:
  - clusterName: cluster1
    name: ingress-1
    namespace: ingress-namespace
    loadBalancerIP: 1.2.3.4
    hostedZoneName: example.com.
  - clusterName: cluster2
    name: ingress-2
    namespace: ingress-namespace
    loadBalancerIP: 5.6.7.8
    hostedZoneName: example.com.
  template:
    spec:
      backend:
        serviceName: backend-service
        servicePort: 80
      rules:
      - host: example.com
        http:
          paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: frontend-service
                port:
                  number: 80

**Comment by aibangjuxin** [comment]
参考：
https://cloud.google.com/kubernetes-engine/docs/concepts/multi-cluster-ingress

https://cloud.google.com/kubernetes-engine/docs/how-to/multi-cluster-ingress

学习上面两篇文章如果我要在在 GKE 中使用MultiClusterIngress
部署端到端 (E2E) 的服务 请给出我详细的部署步骤
并且给出最终如何去验证结果

**部署步骤**

**1. 启用 Multi-Cluster Ingress**

* 在每个要加入 Multi-Cluster Ingress 的集群中，启用 API：

```
gcloud services enable servicecontrol.googleapis.com \
  --project=PROJECT_ID
```

* 创建一个 Multi-Cluster Ingress 资源：

```
kubectl apply -f - <<EOF
apiVersion: networking.gke.io/v1beta1
kind: MultiClusterIngress
metadata:
  name: my-multi-cluster-ingress
  namespace: default
spec:
  ingress:
    hostname: my-multi-cluster-ingress.example.com
  members:
  - cluster: cluster-1
    namespace: default
  - cluster: cluster-2
    namespace: default
EOF
```

**2. 创建 Ingress 对象**

* 在其中一个集群（例如 `cluster-1`）中，创建 Ingress 对象：

```
kubectl apply -f - <<EOF
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: default
  annotations:
    networking.gke.io/multiClusterIngress: "true"
    networking.gke.io/multiClusterIngressHostname: my-multi-cluster-ingress.example.com
spec:
  rules:
  - host: my-ingress.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-service
            port:
              number: 80
EOF
```

**3. 创建 Service 对象**

* 在 `cluster-1` 中创建 Service 对象：

```
kubectl apply -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: default
spec:
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 8080
EOF
```

**4. 部署应用程序**

* 在 `cluster-1` 中部署应用程序：

```
kubectl apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: gcr.io/my-project/my-app:latest
        ports:
        - containerPort: 8080
EOF
```

**验证结果**

* **检查 Ingress 状态：**

```
kubectl get ingress my-ingress -o yaml
```

输出应显示 `ingress.class: gce` 和 `networking.gke.io/multiClusterIngress: true`。

* **检查 Multi-Cluster Ingress 状态：**

```
kubectl get multiclusteringress my-multi-cluster-ingress -o yaml
```

输出应显示 `status.members` 字段，其中列出了所有参与的集群。

* **测试 Ingress：**

使用 DNS 名称 `my-multi-cluster-ingress.example.com` 访问 Ingress。您应该能够看到应用程序的响应。

* **验证跨集群流量：**

使用 `kubectl exec` 命令在每个集群中检查应用程序日志。您应该看到来自所有集群的请求日志。

**Comment by aibangjuxin** [comment]
要在GKE中使用 MultiClusterIngress 部署端到端服务,您需要执行以下步骤:

1. **启用多集群Ingress功能**
   - 在Google Cloud控制台上,导航到 Kubernetes Engine -> 集群
   - 选择您要启用多集群Ingress的集群
   - 编辑集群,勾选"启用多集群Ingress"选项
   - 保存更改

2. **部署示例服务**
   - 为了演示,我们将部署一个简单的nginx服务作为后端服务
   ```yaml
   # nginx-app.yaml
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: nginx-deployment
   spec:
     replicas: 3
     selector:
       matchLabels:
         app: nginx
     template:
       metadata:
         labels:
           app: nginx
       spec:
         containers:
         - name: nginx
           image: nginx
           ports:
           - containerPort: 80
   ---
   apiVersion: v1
   kind: Service
   metadata:
     name: nginx-service
   spec:
     selector:
       app: nginx
     ports:
     - port: 80
   ```
   - `kubectl apply -f nginx-app.yaml`

3. **配置MultiClusterIngress**
   - 创建一个Kubernetes Ingress对象,指定backend为上面创建的nginx服务
   ```yaml
   # ingress.yaml 
   apiVersion: networking.k8s.io/v1
   kind: Ingress 
   metadata:
     name: nginx-ingress
     annotations:
       kubernetes.io/ingress.class: "gce"
       kubernetes.io/ingress.global-static-ip-name: "web-static-ip"
   spec:
     defaultBackend:
       service:
         name: nginx-service
         port: 
           number: 80
   ```
   - `kubectl apply -f ingress.yaml`
   - 这将创建一个全局静态IP用于Ingress

4. **验证结果**
   - 获取全局静态IP `STATIC_IP=$(kubectl get ingress -o jsonpath="{.status.loadBalancer.ingress[0].ip}")`
   - 访问静态IP:`curl http://$STATIC_IP` 
   - 你应该可以看到nginx的默认欢迎页面
   - 此时,你已经通过GCP的全局负载均衡器访问到了后端的nginx服务

5. **跨集群访问(可选)**
   - 如果您有多个集群,可以遵循上述步骤在其他集群中部署相同的nginx服务和Ingress
   - 所有集群中的服务都将通过同一个全局负载均衡器暴露
   - 请求将自动跨集群负载均衡到最近的后端Pod

通过这些步骤,您已经在GKE中成功部署并验证了一个使用MultiClusterIngress的端到端服务。该功能允许您跨多个GKE集群提供高可用和扩展能力的全局Ingress。
