### ISSUE TITLE
Istio

### ISSUE THREAD

**Issue by aibangjuxin** [aibangjuxin/groovy#122]
**Istio 部署类型**

```mermaid
graph LR
subgraph 部署类型
    gateway --> virtualservice
    virtualservice --> destinationrule
    destinationrule --> serviceentry
end
```

**部署类型之间的关系**

* **Gateway：**Istio 网关，负责将外部流量路由到 Istio 服务网格内。
* **VirtualService：**定义如何将流量路由到不同的服务版本或子集。
* **DestinationRule：**指定流量如何到达特定服务，例如超时和重试策略。
* **ServiceEntry：**将外部服务（例如数据库或 API）引入 Istio 服务网格。

**Gateway**

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
```

**VirtualService**

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-virtualservice
spec:
  hosts:
  - my-service.example.com
  gateways:
  - my-gateway
  http:
  - match:
    - uri: /productpage
    route:
    - destination:
        host: my-productpage
        port:
          number: 9080
```

**DestinationRule**

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: my-destinationrule
spec:
  host: my-productpage
  trafficPolicy:
    timeout: 10s
    retry:
      perTryTimeout: 5s
```

**ServiceEntry**

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: my-serviceentry
spec:
  hosts:
  - my-external-service.example.com
  ports:
  - number: 80
    name: http
    protocol: HTTP
  location: MESH_EXTERNAL
  resolution: DNS
```
