### ISSUE TITLE
network policy

### ISSUE THREAD

**Issue by aibangjuxin** [aibangjuxin/groovy#144]
要编写一个Shell脚本来判断Kubernetes命名空间中是否存在某个名字的网络策略（NetworkPolicy），如果存在则更新它，如果不存在则创建它，可以使用`kubectl`命令。以下是一个示例脚本：

```bash
#!/bin/bash

# 定义命名空间和NetworkPolicy的名字
NAMESPACE=$1
NETWORK_POLICY_NAME=$2
NETWORK_POLICY_FILE=$3

# 检查输入参数是否完整
if [ -z "$NAMESPACE" ] || [ -z "$NETWORK_POLICY_NAME" ] || [ -z "$NETWORK_POLICY_FILE" ]; then
  echo "Usage: $0 <namespace> <network_policy_name> <network_policy_file>"
  exit 1
fi

# 检查命名空间中是否存在指定的NetworkPolicy
kubectl get networkpolicy -n $NAMESPACE $NETWORK_POLICY_NAME > /dev/null 2>&1

if [ $? -eq 0 ]; then
  # 如果存在，更新NetworkPolicy
  echo "NetworkPolicy '$NETWORK_POLICY_NAME' exists in namespace '$NAMESPACE'. Updating..."
  kubectl apply -f $NETWORK_POLICY_FILE -n $NAMESPACE
else
  # 如果不存在，创建NetworkPolicy
  echo "NetworkPolicy '$NETWORK_POLICY_NAME' does not exist in namespace '$NAMESPACE'. Creating..."
  kubectl create -f $NETWORK_POLICY_FILE -n $NAMESPACE
fi
```

### 使用方法
将上述脚本保存为文件，例如`update_network_policy.sh`，并确保其可执行：
```bash
chmod +x update_network_policy.sh
```

运行脚本时，需要传递三个参数：命名空间、网络策略的名字和网络策略的YAML文件路径。例如：
```bash
./update_network_policy.sh my-namespace my-network-policy network-policy.yaml
```

### 示例NetworkPolicy文件
以下是一个简单的NetworkPolicy YAML文件示例：

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: my-network-policy
spec:
  podSelector:
    matchLabels:
      role: db
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: frontend
  egress:
  - to:
    - podSelector:
        matchLabels:
          role: backend
```

### 脚本解释
1. **参数检查**：脚本首先检查是否提供了必要的参数：命名空间、网络策略名称和网络策略文件路径。
2. **检查NetworkPolicy**：使用`kubectl get networkpolicy`命令检查指定命名空间中是否存在给定名称的网络策略。
3. **更新或创建**：如果存在，则使用`kubectl apply`更新网络策略；如果不存在，则使用`kubectl create`创建网络策略。

这样，这个脚本可以帮助你自动化管理Kubernetes命名空间中的网络策略。
