### ISSUE TITLE
Auth gcp

### ISSUE THREAD

**Issue by aibangjuxin** [aibangjuxin/groovy#157]
要使用Google Cloud SDK进行身份验证而无需每次都通过浏览器进行手动登录，可以使用服务账户进行身份验证。服务账户可以配置为自动化脚本的凭证，以便脚本可以无缝地访问Google Cloud资源。

以下是使用服务账户JSON密钥文件进行身份验证的步骤：

1. **创建服务账户和密钥文件**：
    1. 转到 [Google Cloud Console](https://console.cloud.google.com/iam-admin/serviceaccounts)。
    2. 创建一个新的服务账户。
    3. 授予该服务账户所需的角色权限，例如`BigQuery Admin`或`BigQuery Data Viewer`。
    4. 创建一个新的密钥，并选择JSON格式。下载该JSON密钥文件。

2. **配置gcloud命令行工具以使用服务账户**：
    将下载的服务账户密钥文件路径设置为环境变量`GOOGLE_APPLICATION_CREDENTIALS`。

    ```sh
    export GOOGLE_APPLICATION_CREDENTIALS="/path/to/your-service-account-file.json"
    ```

3. **使用服务账户进行身份验证**：
    使用服务账户凭证执行身份验证。

    ```sh
    gcloud auth activate-service-account --key-file="$GOOGLE_APPLICATION_CREDENTIALS"
    ```

4. **使用服务账户进行BigQuery查询**：
    现在，您可以使用`bq`命令行工具进行BigQuery查询，而不需要每次都通过浏览器进行手动验证。

    ```sh
    bq query --use_legacy_sql=false 'SELECT * FROM `your-dataset.your-table` LIMIT 10;'
    ```

通过这种方法，您可以在脚本中自动化Google Cloud操作，而不需要每次都通过浏览器进行手动登录。

请注意，如果您必须使用个人帐户而不能使用服务帐户，还有其他方法，例如使用OAuth 2.0刷新令牌或授权设备代码流程，但这些方法通常更复杂且不适合直接在脚本中使用。使用服务账户是最推荐的自动化方法。

**Comment by aibangjuxin** [comment]
在GKE（Google Kubernetes Engine）中，如果你想临时回收一些被Pod占用的内存，可以考虑以下几种方法：

1. **调整Pod的资源限制和请求**：
   - Kubernetes允许你为Pod配置资源请求和限制。资源请求确保Pod有足够的资源，而资源限制则防止Pod使用过多资源。可以通过调整Pod的配置来限制其内存使用。
   ```yaml
   apiVersion: v1
   kind: Pod
   metadata:
     name: mypod
   spec:
     containers:
     - name: mycontainer
       image: myimage
       resources:
         requests:
           memory: "512Mi"
         limits:
           memory: "1Gi"
   ```

2. **使用Vertical Pod Autoscaler (VPA)**：
   - VPA可以自动调整Pod的资源请求和限制，从而帮助管理内存使用。它可以根据Pod的实际使用情况动态调整资源。
   ```yaml
   apiVersion: autoscaling.k8s.io/v1
   kind: VerticalPodAutoscaler
   metadata:
     name: my-vpa
   spec:
     targetRef:
       apiVersion: "apps/v1"
       kind:       Deployment
       name:       my-deployment
     updatePolicy:
       updateMode: "Auto"
   ```

3. **重启Pod**：
   - 重启Pod会释放其占用的所有资源。可以使用Kubernetes的命令来删除并重新创建Pod，从而回收内存。
   ```bash
   kubectl delete pod mypod
   ```

4. **使用节点级别的内存管理工具**：
   - 可以在节点上安装一些内存管理工具，如`oom-killer`或其他Linux内存管理工具，这些工具可以在内存紧张时自动释放或回收内存。

5. **清理缓存**：
   - 在容器内部或节点上执行一些脚本来清理缓存。例如，使用`sync`命令和`echo 3 > /proc/sys/vm/drop_caches`来释放缓存。
   ```bash
   sync; echo 3 > /proc/sys/vm/drop_caches
   ```

6. **调整应用程序代码**：
   - 优化应用程序代码以减少内存使用，特别是对于那些有内存泄漏或不必要的内存占用的应用程序。

请注意，临时回收内存可能会影响应用程序的性能和稳定性，因此在实施这些方法时需要谨慎。

以下是一个示例流程图，描述了在GKE中管理Pod内存的步骤：

```mermaid
flowchart TD
    A[调整Pod的资源限制和请求] --> B[使用Vertical Pod Autoscaler (VPA)]
    A --> C[重启Pod]
    A --> D[使用节点级别的内存管理工具]
    A --> E[清理缓存]
    A --> F[调整应用程序代码]
```

这些方法可以帮助你在需要时回收Pod占用的内存，并保持系统的稳定运行。
