### ISSUE TITLE
Network policy

### ISSUE THREAD

**Issue by aibangjuxin** [aibangjuxin/groovy#28]
graph TD

subgraph Namespace A
  A[应用程序 Pods] -- 入站规则 --> B[Ingress 网络策略]
  A -- 出站规则 --> C[Egress 网络策略]
end

subgraph Namespace B
  D[应用程序 Pods] -- 入站规则 --> E[Ingress 网络策略]
  D -- 出站规则 --> F[Egress 网络策略]
end

subgraph Internet
  G[Internet]
end

B -- 允许流量 --> G
C -- 允许流量 --> G
E -- 允许流量 --> G
F -- 允许流量 --> G

**Comment by aibangjuxin** [comment]
当涉及 Kubernetes Network Policies 时，以下是更多关于 Network Policy 的关键概念和关键字，包括关于 Namespace Selector 的信息：

1. **Ingress**: Ingress 规则定义了允许从其他 Pod 进入受 Network Policy 保护的 Pod 的流量。这是流入 Pod 的流量。

2. **Egress**: Egress 规则定义了允许从受 Network Policy 保护的 Pod 流出的流量。这是流出 Pod 的流量。

3. **Deny**: Deny 规则用于拒绝特定类型的流量，可以用于限制进出 Pod 的流量。

4. **Allow**: Allow 规则用于允许特定类型的流量，这些规则指定哪些流量是被允许的。

5. **Label Selector**: Label Selector 是一种用于选择要受 Network Policy 影响的 Pod 的方法。你可以使用标签选择器来定义规则应用于哪些 Pod。

6. **Pod Selector**: Pod Selector 是 Network Policy 规则的一部分，它定义了规则应该应用于哪些 Pod。通常与 Label Selector 一起使用。

7. **Network Policy Types**: Network Policies可以分为两种主要类型：Ingress Network Policies（入站网络策略）和Egress Network Policies（出站网络策略）。这些类型决定了规则是应用于流入 Pod 还是流出 Pod。

8. **Peer Pods**: Peer Pods 是指受 Network Policy 影响的其他 Pods，它们可以是 Ingress 流量的来源或 Egress 流量的目标。

9. **Port**: Port 规则用于指定允许或拒绝的端口范围。它可以限制哪些端口上的流量是被允许的或被拒绝的。

10. **Default Deny**: 默认拒绝是一种 Network Policy 的实践，其中规则通常从 "Deny All" 开始，然后明确允许需要的流量。这有助于提高网络安全性。

11. **Policy Priority**: 如果多个 Network Policies 应用于相同的 Pod，优先级可用于确定哪个策略的规则将首先应用。

12. **Policy Precedence**: 与优先级类似，Policy Precedence 是规则的执行顺序，可以影响流量是否被允许或拒绝。

13. **Policy Logging**: 有时，Network Policies 具有日志记录功能，允许跟踪哪些流量被允许或拒绝。

14. **Namespace Selector**: Namespace Selector 是 Network Policy 中的组成部分，它用于选择要应用 Network Policy 的命名空间。这使你可以定义规则应用于特定命名空间中的 Pods。

这些关键概念和关键字扩展了关于 Kubernetes Network Policies 的了解，包括了命名空间选择器的重要性。如果你需要更多详细信息或示例，请随时提出。

**Comment by aibangjuxin** [comment]
Of course, we don't stop exploring, we are always paying attention to the needs of our users, and we try to explore new features to provide a better service in conjunction with the services provided by Google.

**Comment by aibangjuxin** [comment]
Of course, we don't stop exploring, we are always paying attention to the needs of our users, and we try our best to explore new features or possibilities with the new features provided by Google in order to provide a better service to our users.

**Comment by aibangjuxin** [comment]
```mermaid
graph TD

subgraph Namespace A
    ingressA((Ingress))
    egressA((Egress))
end

subgraph Namespace B
    ingressB((Ingress))
    egressB((Egress))
end

subgraph Default Deny
    ingressA -->|Deny All| egressA
    ingressB -->|Deny All| egressB
end

subgraph DNS Allow
    ingressA -->|Allow DNS| egressA
    ingressB -->|Allow DNS| egressB
end

subgraph Allow Traffic
    ingressA -->|Allow Traffic| egressB
end
```

**Comment by aibangjuxin** [comment]
```mermaid
graph TD

subgraph Namespace A
    ingressA((Ingress))
    egressA((Egress))
end

subgraph Namespace B
    ingressB((Ingress))
    egressB((Egress))
end

subgraph DefaultDeny
    ingressA -->|Deny All| egressA
    ingressB -->|Deny All| egressB
end

subgraph DNSAllow
    ingressA -->|Allow DNS| egressA
    ingressB -->|Allow DNS| egressB
end

subgraph AllowTraffic
    ingressA -->|Allow Traffic| egressB
end
```

**Comment by aibangjuxin** [comment]
```mermaid
graph TD

subgraph NamespaceA[Namespace A]
    ingressA((Ingress))
    egressA((Egress))
end

subgraph NamespaceB[Namespace B]
    ingressB((Ingress))
    egressB((Egress))
end

subgraph DefaultDeny[Default Deny]
    ingressA -->|Deny All| egressA
    ingressB -->|Deny All| egressB
end

subgraph DNSAllow[Allow DNS]
    ingressA -->|Allow DNS| egressA
    ingressB -->|Allow DNS| egressB
end

subgraph AllowTraffic[Allow Traffic]
    ingressA -->|Allow Traffic| egressB
end
```

**Comment by aibangjuxin** [comment]
graph TD

subgraph NamespaceA[Namespace A]
    ingressA((Ingress))
    egressA((Egress))
end

subgraph NamespaceB[Namespace B]
    ingressB((Ingress))
    egressB((Egress))
end

subgraph DefaultDeny[Default Deny]
    ingressA -->|Deny All| egressA
    ingressB -->|Deny All| egressB
end

subgraph DNSAllow[Allow DNS]
    ingressA -->|Allow DNS| egressA
    ingressB -->|Allow DNS| egressB
end

subgraph AllowTraffic[Allow Traffic]
    ingressA -->|Allow Traffic| egressB
end

**Comment by aibangjuxin** [comment]
graph TD

subgraph NamespaceA[Namespace A - egressA]
    ingressA((Ingress))
end

subgraph NamespaceB[Namespace B]
    egressB((Egress))
end

A -->|Egress| ingressB

```mermaid
graph TD

subgraph NamespaceA[Namespace A - egressA]
    ingressA((Ingress))
end

subgraph NamespaceB[Namespace B]
    egressB((Egress))
end

A -->|Egress| ingressB
```

**Comment by aibangjuxin** [comment]
您不需要为您的 GCE 实例配置单独的路由，以便其可以访问 GKE 中的负载均衡器。默认情况下，GCE 实例可以访问与其所在的子网相同子网中的所有 IP 地址。因此，如果您的 GCE 实例位于 192.168.0.0/18 子网中，它可以访问 192.168.64.0/19 子网中的所有 IP 地址，包括 GKE 负载均衡器的 IP 地址。

但是，如果您希望在 GCE 实例中配置明确的路由，以便其可以更有效地访问 GKE 中的负载均衡器，则可以这样做。为此，您可以创建一个路由表，将 GKE 负载均衡器的 IP 地址映射到其子网的网关 IP 地址。然后，您可以将该路由表附加到您的 GCE 实例。

以下是创建路由表并将其附加到 GCE 实例的步骤：

1. 在 Google Cloud Platform Console 中，转到 **VPC 网络** 页面。
2. 单击您要创建路由表的网络。
3. 在 **路由表** 部分，单击 **创建路由表**。
4. 在 **路由表名称** 字段中，输入路由表的名称。
5. 在 **网关** 字段中，选择 GKE 负载均衡器的子网的网关 IP 地址。
6. 在 **目的地址** 字段中，输入 GKE 负载均衡器的 IP 地址。
7. 单击 **创建**。
8. 选择您的 GCE 实例。
9. 在 **网络** 选项卡上，单击 **附加路由表**。
10. 在 **路由表** 列表中，选择您刚刚创建的路由表。
11. 单击 **保存**。

在创建路由表后，您的 GCE 实例将能够通过其子网的网关 IP 地址访问 GKE 中的负载均衡器。

是的，这两个子网不是同一个范围。但是，在 GCP 中，所有子网都具有通往互联网网关的路由。因此，即使这两个子网不是同一个范围，您的 GCE 实例仍然可以通过互联网网关访问 GKE 中的负载均衡器。

具体来说，您的 GCE 实例将首先将请求发送到互联网网关。互联网网关将将请求转发到 GKE 负载均衡器。GKE 负载均衡器将将请求转发到后端 Pod。

因此，您的 GCE 实例不需要配置单独的路由，以便其可以访问 GKE 中的负载均衡器。

但是，如果您希望在 GCE 实例中配置明确的路由，以便其可以更有效地访问 GKE 中的负载均衡器，则可以这样做。为此，您可以创建一个路由表，将 GKE 负载均衡器的 IP 地址映射到其子网的网关 IP 地址。然后，您可以将该路由表附加到您的 GCE 实例。

在这种情况下，您的 GCE 实例将能够直接将请求发送到 GKE 负载均衡器，而无需通过互联网网关。这可以提高性能，因为它将减少网络流量。

以下是创建路由表并将其附加到 GCE 实例的步骤：

1. 在 Google Cloud Platform Console 中，转到 **VPC 网络** 页面。
2. 单击您要创建路由表的网络。
3. 在 **路由表** 部分，单击 **创建路由表**。
4. 在 **路由表名称** 字段中，输入路由表的名称。
5. 在 **网关** 字段中，选择 GKE 负载均衡器的子网的网关 IP 地址。
6. 在 **目的地址** 字段中，输入 GKE 负载均衡器的 IP 地址。
7. 单击 **创建**。
8. 选择您的 GCE 实例。
9. 在 **网络** 选项卡上，单击 **附加路由表**。
10. 在 **路由表** 列表中，选择您刚刚创建的路由表。
11. 单击 **保存**。

在创建路由表后，您的 GCE 实例将能够直接将请求发送到 GKE 负载均衡器。

**Comment by aibangjuxin** [comment]
要查找和确认您的互联网网关，您可以使用以下步骤：

1. 在 Google Cloud Platform Console 中，转到 **VPC 网络** 页面。
2. 单击您要查找的子网。
3. 在 **网关** 部分，查看 **互联网网关** 字段。

互联网网关的 IP 地址将在 **互联网网关** 字段中列出。您可以使用此 IP 地址来验证您的 GCE 实例是否正在将请求发送到正确的互联网网关。

要验证您的 GCE 实例是否正在将请求发送到正确的互联网网关，您可以使用以下步骤：

1. 在您的 GCE 实例上，使用 `ping` 命令来 ping 互联网网关的 IP 地址。

```
ping <互联网网关 IP 地址>
```

如果您收到响应，则您的 GCE 实例正在将请求发送到正确的互联网网关。

以下是一些示例输出：


PING <互联网网关 IP 地址> (<互联网网关 IP 地址>) 56(84) bytes of data.
64 bytes from <互联网网关 IP 地址> (<互联网网关 IP 地址>): icmp_seq=1 ttl=64 time=2.13 ms
64 bytes from <互联网网关 IP 地址> (<互联网网关 IP 地址>): icmp_seq=2 ttl=64 time=2.20 ms
64 bytes from <互联网网关 IP 地址> (<互联网网关 IP 地址>): icmp_seq=3 ttl=64 time=2.18 ms


如果您没有收到响应，则您的 GCE 实例可能正在使用默认的互联网网关，而不是您指定的互联网网关。您可以通过检查您的 GCE 实例的网络配置来验证这一点。

要检查您的 GCE 实例的网络配置，您可以使用以下步骤：

1. 在 Google Cloud Platform Console 中，转到 **Compute Engine** 页面。
2. 选择您的 GCE 实例。
3. 在 **网络** 选项卡上，查看 **路由表** 部分。

路由表列表将显示您的 GCE 实例所附加的所有路由表。您可以检查这些路由表，以查看它们是否将流量发送到正确的互联网网关。

如果您发现您的 GCE 实例正在使用默认的互联网网关，您可以将其更改为您指定的互联网网关。为此，您可以使用以下步骤：

1. 在 Google Cloud Platform Console 中，转到 **Compute Engine** 页面。
2. 选择您的 GCE 实例。
3. 在 **网络** 选项卡上，单击 **附加路由表**。
4. 在 **路由表** 列表中，选择您指定的路由表。
5. 单击 **保存**。

在您保存更改后，您的 GCE 实例将开始将请求发送到您指定的互联网网关。

**Comment by aibangjuxin** [comment]
如果您在Google Kubernetes Engine（GKE）上创建了一个Service，并将其externalTrafficPolicy设置为Cluster，同时禁止了命名空间的入站和出站流量，则需要创建网络策略（Network Policy）允许节点IP之间的通信。这是因为externalTrafficPolicy设置为Cluster会导致负载均衡器将外部流量直接路由到后端Pod所在的节点上，而不经过Kubernetes集群的网络层。由于您禁止了命名空间的入站和出站流量，节点之间的通信将受到限制。因此，您需要创建网络策略规则来允许节点IP访问Pod的目标端口。

在上述情况下，您可以使用以下Network Policy来允许节点IP之间的通信：

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-node-communication
spec:
  podSelector:
    matchLabels:
      app: nginx
  ingress:
  - from:
    - ipBlock:
        cidr: <node-cidr>
  ports:
  - protocol: TCP
    port: <targetPort>
```

请将`<node-cidr>`替换为您集群中节点的CIDR范围（例如，10.0.0.0/24），将`<targetPort>`替换为实际的目标端口（在您的示例中为80）。

这个网络策略允许来自节点CIDR范围内的IP访问标记为`app: nginx`的Pod的目标端口。这样，负载均衡器就可以将外部流量直接路由到后端Pod所在的节点上，并且节点之间的通信也能够顺利进行。

**Comment by aibangjuxin** [comment]
如果Service的externalTrafficPolicy设置为Cluster,并且默认禁止了命名空间的入站和出站流量,那么对于服务的外部访问,你需要创建NetworkPolicy规则来允许节点IP之间的通信:

- 由于externalTrafficPolicy设置为Cluster,负载均衡器会向集群内所有节点的目标端口进行流量分发,这会导致流量从一个节点传递到另一个节点。

- 默认情况下,不同节点之间的流量是被禁止的,由于命名空间网络隔离策略。

- 所以为了让负载均衡能够正常工作,需要允许节点IP地址之间可以访问pod的目标端口。

- 你提供的NetworkPolicy规则就是用于此目的,它允许来自节点CIDR(即节点IP)的 inbound 流量,可以访问目标端口。

所以总结一下:

- externalTrafficPolicy为Cluster,会导致跨节点流量
- 默认不同节点间流量被禁止  
- 需要NetworkPolicy规则允许节点IP可以访问pod目标端口

这样负载均衡器才能正常进行流量分发到集群各节点上的pod实例。如果不创建此NetworkPolicy,由于节点间流量默认被阻断,负载均衡就无法正常工作了。

**Comment by aibangjuxin** [comment]
您提出了一个很好的问题。直接允许所有GKE节点IP范围访问目标端口 indeed存在一定的安全隐患:

- GKE节点IP范围通常很广,允许整个范围会打开很大的攻击面。如果节点被入侵或标识被盗取,整个范围都可能受到影响。

- 日后节点集群扩容,新增节点IP也会自动加入这个规则范围内,增加不可控风险。

- 某些节点可能存在安全问题,比如镜像更新滞后或者软件有漏洞等,允许其IP范围访问也不是很安全。

为了减少这种安全隐患,可以考虑以下方法:

1. 只允许内网IP段访问,比如10.0.0.0/8。

2. 指定可信任的单个节点IP白名单。

3. 使用NetworkPolicy对端口和来源进行进一步限制,比如只开放必要端口,来源限制在负载均衡IP。

4. 在NetworkPolicy上添加标签选择器,限定目标Pod必须有匹配标签。

5. 使用NetworkPolicy与安全组结合,在防火墙层进行二次验证。 

6. 定期审计和更新NetworkPolicy规则。

7. 配合监控告警,发现无疾而终的连接尝试。

8. 将负载均衡冲出集群,消除集群内节点互访风险

所以为保证安全性,不建议直接打开所有的GKE节点IP范围。可以考虑采取上述一些方法进行限制和隔离,降低网络策略规则带来的潜在风险。

**Comment by aibangjuxin** [comment]
如果想要通过LoadBalancer类型的Service仅提供GCE内部负载均衡器的访问,同时Pod可能在不同节点,那么可以考虑以下设置:

1. 使用internal类型的负载均衡器,externalTrafficPolicy设置为Cluster:

```yaml
apiVersion: v1
kind: Service 
spec:
  type: LoadBalancer 
  loadBalancerSourceRanges: 10.0.0.0/8 # 只允许GCE内网IP访问
  externalTrafficPolicy: Cluster
```

2. 同时创建NetworkPolicy,允许节点IP之间访问目标端口:

```yaml 
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
spec: 
  podSelector: null
  ingress:
  - from:
    - ipBlock:
        cidr: <node-cidr>
    ports: 
    - port: 80
```

3. 可选:限制NetworkPolicy规则范围到内网IP段,比如10.0.0.0/8:

```yaml
spec:
  ingress: 
  - from: 
    - ipBlock: 
        cidr: 10.0.0.0/8
``` 

4. 通过安全组规则限制负载均衡器接口只允许内网IP访问

这样就可以实现:

- 仅通过内部负载均衡器提供服务
- 负载均衡流量可以分发到不同节点上的Pod
- 节点之间和Pod之间流量交互得到允许
- 外部网络无法直接访问负载均衡器

保障服务内部可访问,外部网络隔离。

这里是一个完整的yaml示例,实现仅通过GCE内部负载均衡器提供服务,同时允许负载均衡流量分发到不同节点上的Pod:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec: 
  type: LoadBalancer
  loadBalancerSourceRanges: 10.0.0.0/8 
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    targetPort: 80
  selector: 
    app: nginx
```

**Comment by aibangjuxin** [comment]
是的，Kubernetes 的 Service 资源对象中有一个名为 `loadBalancerSourceRanges` 的选项，它用于限制可以访问 LoadBalancer 类型服务的源 IP 范围。

`loadBalancerSourceRanges` 选项允许您指定一个 IP 范围，只有位于该范围内的请求才能访问 LoadBalancer 服务。这可以用于增加服务的安全性，限制访问来源。

以下是一个示例 Service 资源定义，展示了如何使用 `loadBalancerSourceRanges` 选项：

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 192.168.0.0/24
    - 10.0.0.0/16
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: my-app
```

在上面的示例中，`loadBalancerSourceRanges` 设置为两个 IP 范围：`192.168.0.0/24` 和 `10.0.0.0/16`。只有源 IP 在这两个范围内的请求才能访问该 LoadBalancer 服务。

请注意，`loadBalancerSourceRanges` 选项只适用于云提供商支持的 LoadBalancer 类型服务，且该云提供商的负载均衡器支持源 IP 管理。不同的云提供商和负载均衡器实现可能会略有不同，请根据您使用的云平台和负载均衡器的文档进行进一步的了解和配置。
