### ISSUE TITLE
konnectivity-agent

### ISSUE THREAD

**Issue by aibangjuxin** [aibangjuxin/groovy#29]
在Google的GCP工程中，我安装了GKE，从1.27开始，konnectivity-agent.我想了解下这个的用途是什么？我注意到其需要开启8123端口？那么对于这个端口针对的是networkpolicy还是GCE的firewall？

对konnectivity-agent的作用和端口使用的总结如下:

- konnectivity-agent是GKE中实现网络策略(NetworkPolicy)的一个关键组件。它会在每个节点上运行,负责实施网络策略规则。

- konnectivity-agent需要开启node的8123端口,这个端口用于konnectivity-agent之间的通信,实现节点间网络策略同步。

- 8123端口与网络策略相关,与GCE firewall无关。网络策略是通过konnectivity-agent在Kubernetes层面实现的。

- 启用网络策略后,需要在所有节点上开启8123端口,以确保konnectivity-agent可以在节点间通信。

- 此外,konnectivity-agent还需要访问10250端口获取pod网络信息。

所以总结下,8123端口用于konnectivity-agent通信,与网络策略直接相关,需要开启该端口来实现GKE上的网络策略。不涉及GCE firewall层面。

好的,如果要专门允许konnectivity-agent的流量,可以这样写NetworkPolicy:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy 
metadata:
  name: allow-konnectivity-agent
spec:
  podSelector:
    matchLabels:
      app: konnectivity-agent
  policyTypes:
  - Ingress 
  - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: konnectivity-agent
      ports:
        - protocol: TCP
          port: 8123
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: konnectivity-agent
      ports:
        - protocol: TCP
          port: 8123
```

这个NetworkPolicy选择匹配标签`app: konnectivity-agent`的Pod,允许其之间的8123端口流量。

也可以写成直接允许所有Namespace的konnectivity-agent通信:

```yaml
ingress:
  - from: 
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app: konnectivity-agent
```

以上示例将允许konnectivity-agent Pod之间的流量,从而实现网络策略。可以根据具体需要调整 NetworkPolicy。
