### ISSUE TITLE
Downward API

### ISSUE THREAD

**Issue by aibangjuxin** [aibangjuxin/groovy#39]
Kubernetes Downward API允许Pod中的容器获取自身Pod的信息,而不需要通过环境变量或配置文件进行传递。主要有以下几个功能:

1. pod name和namespace

容器可以通过环境变量获取Pod的name和namespace:

```yaml
env:
- name: MY_POD_NAME
  valueFrom:
    fieldRef:
      fieldPath: metadata.name
- name: MY_POD_NAMESPACE
  valueFrom:
    fieldRef:
      fieldPath: metadata.namespace
```

2. Pod IP地址

容器可以通过环境变量获取Pod的IP地址:

```yaml  
env:
- name: MY_POD_IP
  valueFrom:
    fieldRef:
      fieldPath: status.podIP
```

3. 容器资源限制

容器可以获取自身的CPU和内存资源限制:

```yaml
env:
- name: MY_CPU_LIMIT
  valueFrom:
    resourceFieldRef:
      resource: limits.cpu
- name: MY_MEM_LIMIT
  valueFrom:
    resourceFieldRef:
      resource: limits.memory
```

4. 标签和注解

容器可以访问Pod的标签和注解:

```yaml
env:
- name: MY_POD_LABEL
  valueFrom:
    fieldRef:
      fieldPath: metadata.labels['mylabel']
- name: MY_POD_ANNOTATION 
  valueFrom:
    fieldRef:
      fieldPath: metadata.annotations['myannotation']  
```

5. 其他字段

还可以访问Pod Spec中的其它字段,例如nodeName,serviceAccountName等。

Downward API为容器提供了直接访问自身Pod信息的能力,避免了通过配置文件传递的复杂性,使应用程序更简单。
