### ISSUE TITLE
Istio

### ISSUE THREAD

**Issue by aibangjuxin** [aibangjuxin/groovy#43]
如果你希望在 Kubernetes 中的 Deployment 启动时不使用 Istio 代理，你可以通过在 Deployment 的 Pod 模板中添加注释来实现。这个注释告诉 Istio 不要自动注入 Istio 代理。

在你的 Deployment YAML 文件中，可以添加以下注释：

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false" # 关闭 Istio 代理注入
    spec:
      containers:
      - name: my-container
        image: my-image
        # ... 其他容器配置 ...
```

在上述示例中，我们在 Pod 模板的 `metadata` 下添加了一个注释 `sidecar.istio.io/inject: "false"`，这告诉 Istio 不要自动注入 Istio 代理到这个 Pod 中。这将确保该容器在启动时不使用 Istio 代理。

请确保将上述注释添加到你的 Deployment YAML 文件中，并根据你的实际需要进行配置。这样，你的容器将在启动时不使用 Istio。
