### ISSUE TITLE
Kubectl exec

### ISSUE THREAD

**Issue by aibangjuxin** [aibangjuxin/groovy#69]
如果你想基于特定的命名空间来限制禁止 `kubectl exec`，你可以使用 RBAC 规则。下面是一个完整的例子和配置，其中我将创建一个 Role 和 RoleBinding 来限制 `kubectl exec` 在特定命名空间中的执行。

首先，创建一个 Role 来定义权限和限制 `exec`：

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: your-namespace
  name: no-exec-role
rules:
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["list", "get"] # 允许 list 和 get 操作，不包括 exec
```

- `your-namespace` 是你要限制的命名空间。
- `no-exec-role` 是你为该角色选择的名称。

接下来，创建一个 RoleBinding 将该角色绑定到特定的 ServiceAccount：

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: no-exec-role-binding
  namespace: your-namespace
subjects:
- kind: ServiceAccount
  name: your-service-account
  namespace: your-namespace
roleRef:
  kind: Role
  name: no-exec-role
  apiGroup: rbac.authorization.k8s.io
```

- `no-exec-role-binding` 是你为该角色绑定选择的名称。
- `your-service-account` 是你想要限制的 ServiceAccount 的名称。

应用这两个配置文件，确保它们位于正确的命名空间 (`your-namespace`)。这将限制特定 ServiceAccount 在指定命名空间中只能执行 `kubectl exec` 命令的 `list` 和 `get` 操作，而不允许实际执行命令。

请确保替换上述示例中的 `your-namespace` 和 `your-service-account` 为你实际使用的命名空间和 ServiceAccount 名称。如果需要更多帮助或有其他特定要求，请提供更详细的信息，以便我提供更具体的示例或流程图。
