### ISSUE TITLE
750

### ISSUE THREAD

**Issue by aibangjuxin** [aibangjuxin/groovy#82]
我有下面这一个hpa配置
关于
averageUtilization: 750
我想了解一下，设置成750和设置成75 有什么对应的区别？
另外，这个值的设置是不是需要和deployment 里面的resources request 或者limits 有对应关系？
```yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
name: name-version-master-1-1-deployment-hpa
namespace: default
spec:
maxReplicas: 2
metrics:
- resource:
name: cpu
target:
averageUtilization: 750
type: Utilization
type: Resource
minReplicas: 1
scaleTargetRef:
apiVersion: apps/v1
kind: Deployment
name: name-version-master-1-1-deployment
``` 
我现在测试的结果是这样的，
假如averageUtilization设置成750
那么这个750 describe pod 是750%
比如我的pod request 设置为100m
那么也就是说，当我的数量达到750m的时候 会出发对应的pod 扩展 但是如果我设置成75的时候 这好像仅仅代表的是75m 当我pod cpu 使用量大于75m的时候，他就会自动扩展

您的理解是正确的。

averageUtilization 的值表示相对于资源请求(request)的利用率。

如果设置为750,则表示当 Pod 的平均 CPU 利用率达到请求量(request)的750%时会触发扩容。例如请求量(request)为100m,那么利用率达到750m时会触发。

如果设置为75,则表示当平均利用率达到请求量的75%时会触发。例如请求量为100m,利用率达到75m时会触发。

所以这个指标需要与部署(Deployment)的资源请求量对应起来设定。

另外,如果没有设置资源请求量,则是相对于资源限制(limit)的利用率。

所以设置这个指标的时候需要考虑应用的资源请求或限制的量,按照实际需要进行扩容的利用率来设定。太高或太低都不合适。

那就是假如我的request 设置为200m 而我的Pod 真正的使用量，比如是100m 如果我的参数设置为其75 那么当我的pod 的使用量达到150 也就是200*75的时候 会出发拉取新的pod?

是的,您的理解是正确的。

如果:

- 资源请求(request)为 200m
- 平均利用率阈值(averageUtilization)设置为75

那么当 Pod 的平均 CPU 利用量达到 200m * 75% = 150m 时,就会触发 Pod 的扩容。

当前 Pod 的实际利用量是否达到 100m 不影响判断。HPA 是根据资源请求量的利用率阈值来决定是否扩容的。

所以这个指标设置需要结合应用的实际资源需求情况来设置合适的资源请求量和利用率阈值,这样才能实现合理的自动扩缩容。
